/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnCommunityRouteImport } from './routes/en/community'
import { Route as EnSponsorRouteImport } from './routes/en/sponsor'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as EnProgramsIndexRouteImport } from './routes/en/programs/index'
import { Route as EnProgramsSlugRouteImport } from './routes/en/programs/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCommunityRoute = EnCommunityRouteImport.update({
  id: '/en/community',
  path: '/en/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSponsorRoute = EnSponsorRouteImport.update({
  id: '/en/sponsor',
  path: '/en/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProgramsIndexRoute = EnProgramsIndexRouteImport.update({
  id: '/en/programs/',
  path: '/en/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProgramsSlugRoute = EnProgramsSlugRouteImport.update({
  id: '/en/programs/$slug',
  path: '/en/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/sponsor': typeof SponsorRoute
  '/en/about': typeof EnAboutRoute
  '/en/community': typeof EnCommunityRoute
  '/en/sponsor': typeof EnSponsorRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/en/': typeof EnIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/en/programs/$slug': typeof EnProgramsSlugRoute
  '/en/programs/': typeof EnProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/sponsor': typeof SponsorRoute
  '/en/about': typeof EnAboutRoute
  '/en/community': typeof EnCommunityRoute
  '/en/sponsor': typeof EnSponsorRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/en': typeof EnIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/en/programs/$slug': typeof EnProgramsSlugRoute
  '/en/programs': typeof EnProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/sponsor': typeof SponsorRoute
  '/en/about': typeof EnAboutRoute
  '/en/community': typeof EnCommunityRoute
  '/en/sponsor': typeof EnSponsorRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/en/': typeof EnIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/en/programs/$slug': typeof EnProgramsSlugRoute
  '/en/programs/': typeof EnProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/sponsor'
    | '/en/about'
    | '/en/community'
    | '/en/sponsor'
    | '/programs/$slug'
    | '/en/'
    | '/programs/'
    | '/en/programs/$slug'
    | '/en/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/sponsor'
    | '/en/about'
    | '/en/community'
    | '/en/sponsor'
    | '/programs/$slug'
    | '/en'
    | '/programs'
    | '/en/programs/$slug'
    | '/en/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/sponsor'
    | '/en/about'
    | '/en/community'
    | '/en/sponsor'
    | '/programs/$slug'
    | '/en/'
    | '/programs/'
    | '/en/programs/$slug'
    | '/en/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  SponsorRoute: typeof SponsorRoute
  EnAboutRoute: typeof EnAboutRoute
  EnCommunityRoute: typeof EnCommunityRoute
  EnSponsorRoute: typeof EnSponsorRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  EnProgramsSlugRoute: typeof EnProgramsSlugRoute
  EnProgramsIndexRoute: typeof EnProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/community': {
      id: '/en/community'
      path: '/en/community'
      fullPath: '/en/community'
      preLoaderRoute: typeof EnCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sponsor': {
      id: '/en/sponsor'
      path: '/en/sponsor'
      fullPath: '/en/sponsor'
      preLoaderRoute: typeof EnSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/programs/': {
      id: '/en/programs/'
      path: '/en/programs'
      fullPath: '/en/programs/'
      preLoaderRoute: typeof EnProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/programs/$slug': {
      id: '/en/programs/$slug'
      path: '/en/programs/$slug'
      fullPath: '/en/programs/$slug'
      preLoaderRoute: typeof EnProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  SponsorRoute: SponsorRoute,
  EnAboutRoute: EnAboutRoute,
  EnCommunityRoute: EnCommunityRoute,
  EnSponsorRoute: EnSponsorRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  EnIndexRoute: EnIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  EnProgramsSlugRoute: EnProgramsSlugRoute,
  EnProgramsIndexRoute: EnProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
